/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "employee.h"
#include<sqlite3.h>
#include<stdio.h>
int z=1;
static int callback(void *notused,int ncol,char** colinrow,char ** colname)
{
	int i;
		printf("full details of employee %d:\n",z++);
	for(i=0;i<ncol;i++)
		printf("%s=%s\n",colname[i],colinrow[i]?colinrow[i]:"null");
	return 0;
}
////////////////////////////////////////////////////////////////////////////////
char **
operation1_1_svc(struct details *argp, struct svc_req *rqstp)
{
	static char * result1;
	sqlite3 *db;
	char *errmsg=0;
	int rc,opendb=1;
	char *sql;
	opendb=sqlite3_open("mohan.db",&db);
	if(opendb==0)
	{
		sql="select * from details;";
		rc=sqlite3_exec(db,sql,0,0,&errmsg);
		if(rc)
		{
			sql="create table details(name char(20),id int,phone char(15),city char(20),pincode int);";
			rc=sqlite3_exec(db,sql,0,0,&errmsg);
			if(rc)
			{
				result1=sqlite3_mprintf("sql error:%s\n",errmsg);
				sqlite3_free(errmsg);
				sqlite3_close(db);
			}
			else
			{
				printf("table created successfully\n");
				sql=sqlite3_mprintf("insert into details values('%s',%d,'%s','%s',%d)",argp->name,argp->id,argp->phone,argp->city,argp->pincode);
				rc=sqlite3_exec(db,sql,callback,0,&errmsg);
				if(rc)
				{
					result1=sqlite3_mprintf("sql error:%s\n",errmsg);
					sqlite3_free(errmsg);
					sqlite3_close(db);
				}
				else
				{
					result1=sqlite3_mprintf("inserted data successfully\n");
					sqlite3_close(db);
				}
			}
		}
		else
		{
			sql=sqlite3_mprintf("insert into details values('%s',%d,'%s','%s',%d)",argp->name,argp->id,argp->phone,argp->city,argp->pincode);
			rc=sqlite3_exec(db,sql,callback,0,&errmsg);
			if(rc)
			{
				result1=sqlite3_mprintf("sql error:%s\n",errmsg);
				sqlite3_free(errmsg);
				sqlite3_close(db);		
			}
			else
			{
				result1=sqlite3_mprintf("inserted data successfully\n");
				sqlite3_close(db);
			}
		}
	}		
	else
	{
		result1=sqlite3_mprintf("cant open database:%s\n",sqlite3_errmsg(db));
	}
	return &result1;
}
////////////////////////////////////////////////////////////////////////////////
char **
operation2_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result2;
	sqlite3 *db;
	char *errmsg=0;
	int rc,opendb=1;
	char *sql;
	opendb=sqlite3_open("mohan.db",&db);
	if(opendb==0)
	{
		sql="select * from details;";
		rc=sqlite3_exec(db,sql,callback,0,&errmsg);
		if(rc)
		{
			result2=sqlite3_mprintf("sql error:%s\n",errmsg);
			sqlite3_free(errmsg);
			sqlite3_close(db);
		}
		else
		{
			sql=sqlite3_mprintf("delete from details where %s",*argp);
			rc=sqlite3_exec(db,sql,callback,0,&errmsg);
			if(rc)
			{
				result2=sqlite3_mprintf("sql error:%s\n",errmsg);
				sqlite3_free(errmsg);
				sqlite3_close(db);
			}
			else
			{
				result2=sqlite3_mprintf("deleted data successfully\n");
				sqlite3_close(db);
			}
		}
	}
	else
	{
		result2=sqlite3_mprintf("cant open database:%s\n",sqlite3_errmsg(db));
	}
	return &result2;
}
////////////////////////////////////////////////////////////////////////////////
char **
operation3_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result3;
	sqlite3 *db;
	char *errmsg=0;
	int rc,opendb=1;
	char *sql;
	opendb=sqlite3_open("mohan.db",&db);
	if(opendb==0)
	{
		sql="select * from details;";
		rc=sqlite3_exec(db,sql,0,0,&errmsg);
		if(rc)
		{
			result3=sqlite3_mprintf("sql error:%s\n",errmsg);
			sqlite3_free(errmsg);
			sqlite3_close(db);
		}
		else
		{
			sql=sqlite3_mprintf("%s",*argp);
			rc=sqlite3_exec(db,sql,callback,0,&errmsg);
			if(rc)
			{
				result3=sqlite3_mprintf("sql error:%s\n",errmsg);
				sqlite3_free(errmsg);
				sqlite3_close(db);
			}
			else
			{
				result3=sqlite3_mprintf("deleted all data successfully\n");
				sqlite3_close(db);
			}
		}
	}
	else
	{
		result3=sqlite3_mprintf("cant open database:%s\n",sqlite3_errmsg(db));
	}
	return &result3;
}
////////////////////////////////////////////////////////////////////////////////
char **
operation4_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result4;

	result4=sqlite3_mprintf("select * from details where %s;",*argp);

	return &result4;
}
////////////////////////////////////////////////////////////////////////////////
char **
operation5_1_svc(char **argp, struct svc_req *rqstp)
{
	static char * result5;

	result5=sqlite3_mprintf("%s",*argp);

	return &result5;
}
